feat(connector-besu): add get past logs method
hyperledger/cactus pull request #1042
Opened 2021-06-15 20:15 UTC by awadhana

Signed-off-by: Hana Awad <awadhana0825@gmail.com>

2021-06-16 23:13 UTC, takeutak approved these changes

2021-06-21 22:05 UTC, petermetz requested changes

2021-06-21 22:05 UTC, petermetz commented on packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
> +// export interface Log{
@awadhana I commented on the other PR accidentally but it was meant to be done here: please remove the commented interface definition here (no reason to keep it around)

2021-07-01 05:22 UTC, petermetz approved these changes

2021-07-02 01:31 UTC, merged