feat(core-api): plugin async initializer method
hyperledger/cactus pull request #1057
Opened 2021-06-17 12:38 UTC by TonyRowntree

Signed-off-by: TonyRowntree <33454202+TonyRowntree@users.noreply.github.com>

**Added** 

- onPluginInit(): Promise<unknown> to the core-api interface.
- no-op onPluginInit method to all plugins main class.

resolves #1035

2021-06-21 23:19 UTC, petermetz requested changes

2021-06-21 23:19 UTC, petermetz commented on packages/cactus-core/src/test/typescript/unit/plugin-registry.test.ts
> +        throw new Error("not sure how this works");
@TonyRowntree You can make this a no-op as well AFAICT (unless you want to specifically test what happens if the initializer throws - which is not a bad idea by the way)

2021-06-21 23:20 UTC, petermetz commented
@TonyRowntree Please rebase+squash into a single commit

2021-06-22 07:36 UTC, kikoncuo approved these changes

2021-06-23 09:18 UTC, takeutak approved these changes

2021-06-23 09:20 UTC, takeutak commented
It looks LGTM now. But I will review it again after Peter's change-request.

2021-06-25 02:17 UTC, petermetz approved these changes

2021-06-26 16:25 UTC, merged