feat(connector-besu): add getPastLogs web service
hyperledger/cactus pull request #1079
Opened 2021-06-21 20:42 UTC by awadhana

Fixes #1067 
Depends on #1042

2021-06-21 21:29 UTC, petermetz requested changes

2021-06-21 21:29 UTC, petermetz commented on packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
> +// export interface Log{
@awadhana Forgot to mention this today: Please remove this leftover code (the commented out interface definition)

2021-07-01 16:41 UTC, petermetz approved these changes
@awadhana LGTM, please keep an eye out for the parent PR (#1067) and once that one has been merged, then we can merge this one as well (it mustn't be merged prior to that other one)

2021-07-02 02:48 UTC, takeutak approved these changes

2021-07-03 00:46 UTC, petermetz commented
@awadhana @ty-lazar Conflict resolution time! :-)

2021-07-08 04:24 UTC, merged