feat(connector-besu): add getBaance web service
hyperledger/cactus pull request #1085
Opened 2021-06-23 15:36 UTC by Leeyoungone

Fixes #1066

@petermetz Mr.Tyler helped me with the test cases!

2021-06-25 02:50 UTC, petermetz requested changes

2021-06-25 02:50 UTC, petermetz commented on packages/cactus-plugin-ledger-connector-besu/src/main/json/openapi.json
> +                "summary": "detailed text here",
@Leeyoungone  A little more details please :-)

2021-06-25 02:50 UTC, petermetz commented on packages/cactus-test-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-validator-besu/get-balance-endpoint.test.ts
> +  t.true(res.data.balance, "Response is String ok");
@Leeyoungone You are missing a `typeof` here, you want to assert that the typeof res.data.balance === "string" is true

2021-06-26 16:50 UTC, petermetz approved these changes

2021-06-26 16:51 UTC, petermetz commented
@Leeyoungone Thank you for the updates, last thing to do is resolve the merge conflicts. :-)

2021-06-28 05:58 UTC, takeutak approved these changes

2021-06-28 23:16 UTC, merged