refactor(core-api): fixes syntax issues
hyperledger/cactus pull request #1173
Opened 2021-07-27 20:15 UTC by twiggins120

fixes #478

2021-07-28 00:06 UTC, petermetz requested changes
@twiggins120 Please squash both commits together and update the PR title to match the first commit (the one that has the matching commit message as the GH issue title).

Looked at the CI logs, the test failure indicates that there is a similar issue elsewhere in the code regarding JSON de/serialization, so the fix for that will be likely the same that you've applied earlier.

See the CI logs for reference:

```sh
  not ok 5 SyntaxError: Unexpected token o in JSON at position 1
      ---
        operator: error
        at: bound (/home/runner/work/cactus/cactus/node_modules/tape-promise/node_modules/onetime/index.js:30:12)
        stack: |-
          SyntaxError: Unexpected token o in JSON at position 1
              at JSON.parse (<anonymous>)
              at PluginLedgerConnectorBesu.deployContract (/home/runner/work/cactus/cactus/packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts:29:39)
              at processTicksAndRejections (internal/process/task_queues.js:97:5)
              at /home/runner/work/cactus/cactus/packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/deploy-contract-from-json.test.ts:172:23
      ...
```

2021-07-28 15:25 UTC, twiggins120 commented
@petermetz On it.

2021-07-28 20:48 UTC, petermetz commented
@twiggins120 

Test that's failing: packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/get-record-locator.test.ts:148:23

```sh
    [2021-07-28T15:56:52.756Z] DEBUG (PluginLedgerConnectorBesu): Received preliminary receipt from Besu node.
    [2021-07-28T15:56:52.757Z] DEBUG (PluginLedgerConnectorBesu): Keychain has the contract, updating networks...
    not ok 5 SyntaxError: Unexpected token o in JSON at position 1
      ---
        operator: error
        at: bound (/home/runner/work/cactus/cactus/node_modules/tape-promise/node_modules/onetime/index.js:30:12)
        stack: |-
          SyntaxError: Unexpected token o in JSON at position 1
              at JSON.parse (<anonymous>)
              at PluginLedgerConnectorBesu.deployContract (/home/runner/work/cactus/cactus/packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts:29:39)
              at processTicksAndRejections (internal/process/task_queues.js:97:5)
              at /home/runner/work/cactus/cactus/packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/get-record-locator.test.ts:148:23
      ...
    # getBesuRecord test 1
    [2021-07-28T15:56:52.848Z] DEBUG (PluginLedgerConnectorBesu): Starting web3.eth.sendSignedTransaction(rawTransaction) 
    [2021-07-28T15:56:54.098Z] DEBUG (PluginLedgerConnectorBesu): Received preliminary receipt from Besu node.
    [2021-07-28T15:56:54.156Z] DEBUG (GetBesuRecordEndpointV1): post - /api/v1/plugins/@hyperledger/cactus-plugin-ledger-connector-besu/get-besu-record
    Bail out! SyntaxError: Unexpected token o in JSON at position 1
```

2021-07-29 23:30 UTC, petermetz commented
🌈 SUMMARY RESULTS 🌈  
                         

 SKIP  packages/cactus-common/src/test/typescript/unit/key-converter.test.ts > no tests found 3s
 SKIP  packages/cactus-common/src/test/typescript/unit/logging/logger.test.ts > no tests found 3s
 FAIL  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/invoke-contract.test.ts 3 failed of 7 16s
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 SKIP  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/unit/chain-code-compiler.test.ts > no tests found 5s
 FAIL  packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/deploy-contract-from-json-xdai.test.ts 4 failed of 12 15m
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ Error: "gas" is missing
Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
 ✖ Total Transaction Count of 9 recorded as expected. RESULT OK.

 FAIL  packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/invoke-contract-xdai.test.ts 3 failed of 7 13m
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ Error: "gas" is missing
Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint-invalid.test.ts 1 failed of 2 
18s
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint.test.ts 1 failed of 2 17s
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts 2 failed of 3 26s
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/initialize-endpoint.test.ts 1 failed of 3 26s
 ✖ Error: Request failed with status code 400

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/new-contract-endpoint.test.ts 2 failed of 3 26s
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/refund-endpoint.test.ts 2 failed of 3 26s
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/withdraw-endpoint.test.ts 2 failed of 3 27s
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 PASS  packages/cactus-test-tooling/src/test/typescript/unit/api-surface.test.ts 2 OK 46.48ms

                         
  🌈 SUMMARY RESULTS 🌈  
                         

 SKIP  packages/cactus-common/src/test/typescript/unit/key-converter.test.ts > no tests found 3s
 SKIP  packages/cactus-common/src/test/typescript/unit/logging/logger.test.ts > no tests found 3s
 FAIL  packages/cactus-plugin-ledger-connector-besu/src/test/typescript/integration/plugin-ledger-connector-besu/deploy-contract/invoke-contract.test.ts 3 failed of 7 16s
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 SKIP  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/unit/chain-code-compiler.test.ts > no tests found 5s
 FAIL  packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/deploy-contract-from-json-xdai.test.ts 4 failed of 12 15m
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ Error: "gas" is missing
Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
 ✖ Total Transaction Count of 9 recorded as expected. RESULT OK.

 FAIL  packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/invoke-contract-xdai.test.ts 3 failed of 7 13m
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ Error: "gas" is missing
Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint-invalid.test.ts 1 failed of 2 
18s
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint.test.ts 1 failed of 2 17s
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts 2 failed of 3 26s
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/initialize-endpoint.test.ts 1 failed of 3 26s
 ✖ Error: Request failed with status code 400

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/new-contract-endpoint.test.ts 2 failed of 3 26s
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/refund-endpoint.test.ts 2 failed of 3 26s
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/withdraw-endpoint.test.ts 2 failed of 3 27s
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 SKIP  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/data-test.ts > no tests found 2s
 FAIL  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-single-status-endpoint-invalid.test.ts 1 failed of 2 2m
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 FAIL  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-single-status-endpoint.test.ts 1 failed of 2 2m
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 FAIL  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-status-endpoint-invalid.test.ts 1 failed of 2 2m
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 FAIL  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/get-status-endpoint.test.ts 1 failed of 2 2m
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 FAIL  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/initialize-endpoint.test.ts 1 failed of 2 2m
 ✖ SyntaxError: Unexpected token o in JSON at position 1

 FAIL  packages/cactus-test-plugin-htlc-eth-besu/src/test/typescript/integration/plugin-htlc-eth-besu/new-contract-endpoint-invalid.test.ts 1 failed of 2 2m
 ✖ S [...]

2021-07-30 19:53 UTC, petermetz commented
```sh
FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint-invalid.test.ts
 ✖ SyntaxError: Unexpected token o in JSON at position 1

  test: packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint-invalid.test.ts
  operator: error
  at: bound
    (***************cactus-scratch-2/node_modules/tape-promise/node_modules/onetime/index.js:30:12)
  stack: >-
    SyntaxError: Unexpected token o in JSON at position 1
        at JSON.parse (<anonymous>)
        at PluginLedgerConnectorBesu.deployContract (***************cactus-scratch-2/packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts:29:39)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at ***************cactus-scratch-2/packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint-invalid.test.ts:163:26

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint-invalid.test.ts 1 failed of 5 17s
 ✖ SyntaxError: Unexpected token o in JSON at position 1

packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint.test.ts 2> [2021-07-30T19:11:54.550Z] WARN (PluginKeychainMemory): Never use PluginKeychainMemory in production. It does not support encryption. It stores everything in plain text.
packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint.test.ts 1> [2021-07-30T19:11:54.550Z] INFO (PluginKeychainMemory): Created PluginKeychainMemory. KeychainID=74f03e48-7311-4d5f-87c6-ffa2a4994f57
packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint.test.ts 2> (node:220238) [DEP0152] DeprecationWarning: Custom PerformanceEntry accessors are deprecated. Please use the detail property.
packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint.test.ts 2> (Use `node --trace-deprecation ...` to show where the warning was created)
 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint.test.ts
 ✖ SyntaxError: Unexpected token o in JSON at position 1

  test: packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint.test.ts
  operator: error
  at: bound
    (***************cactus-scratch-2/node_modules/tape-promise/node_modules/onetime/index.js:30:12)
  stack: >-
    SyntaxError: Unexpected token o in JSON at position 1
        at JSON.parse (<anonymous>)
        at PluginLedgerConnectorBesu.deployContract (***************cactus-scratch-2/packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts:29:39)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at ***************cactus-scratch-2/packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint.test.ts:162:26

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-single-status-endpoint.test.ts 1 failed of 5 18s
 ✖ SyntaxError: Unexpected token o in JSON at position 1

packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts 2> [2021-07-30T19:12:13.116Z] WARN (PluginKeychainMemory): Never use PluginKeychainMemory in production. It does not support encryption. It stores everything in plain text.
packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts 1> [2021-07-30T19:12:13.115Z] INFO (PluginKeychainMemory): Created PluginKeychainMemory. KeychainID=bf8b06c9-b5db-4a77-9e19-a832443f2184
packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts 2> (node:221186) [DEP0152] DeprecationWarning: Custom PerformanceEntry accessors are deprecated. Please use the detail property.
packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts 2> (Use `node --trace-deprecation ...` to show where the warning was created)
packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts 2> [2021-07-30T19:12:22.395Z] WARN (PluginKeychainMemory): Never use PluginKeychainMemory in production. It does not support encryption. It stores everything in plain text.
 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts
 ✖ SyntaxError: Unexpected token o in JSON at position 1

  test: packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts
  operator: error
  at: bound
    (***************cactus-scratch-2/node_modules/tape-promise/node_modules/onetime/index.js:30:12)
  stack: >-
    SyntaxError: Unexpected token o in JSON at position 1
        at JSON.parse (<anonymous>)
        at PluginLedgerConnectorBesu.deployContract (***************cactus-scratch-2/packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts:29:39)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at ***************cactus-scratch-2/packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts:162:26

packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts 1> [2021-07-30T19:12:22.394Z] INFO (PluginKeychainMemory): Created PluginKeychainMemory. KeychainID=92fd3933-abdb-4280-9e06-831cb44228b8
 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts
 ✖ SyntaxError: Unexpected token o in JSON at position 1

  test: packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts
  operator: error
  at: bound
    (***************cactus-scratch-2/node_modules/tape-promise/node_modules/onetime/index.js:30:12)
  stack: >-
    SyntaxError: Unexpected token o in JSON at position 1
        at JSON.parse (<anonymous>)
        at PluginLedgerConnectorBesu.deployContract (***************cactus-scratch-2/packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts:29:39)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at ***************cactus-scratch-2/packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts:381:26

 FAIL  packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/get-status-endpoint.test.ts 2 failed of 9 28s
 ✖ SyntaxError: Unexpected token o in JSON at position 1
 ✖ SyntaxError: Unexpected token o in JSON at position 1

packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/initialize-endpoint.test.ts 2> [2021-07-30T19:12:40.707Z] WARN (PluginKeychainMemory): Never use PluginKeychainMemory in production. It does not support encryption. It stores everything in plain text.
packages/cactus-test-plugin-htlc-eth-b [...]

2021-08-03 02:36 UTC, petermetz approved these changes

2021-08-03 05:32 UTC, takeutak approved these changes

2021-08-03 15:05 UTC, merged