refactor: remap ts typings from types to lib
hyperledger/cactus pull request #1193
Opened 2021-08-09 21:03 UTC by Leeyoungone

This was necessary because if we import JSON files and
then re-use their schema as types, then the d.ts files
will need to have access to said JSON file which does
not happen if the typings and the actual .js code are
in separate directories because then the relative paths
are not working as they should.

Moving the lib and the types together means that now
the d.ts files can import with the same relative paths
that the orignial source code (.ts files) can as well.

Signed-off-by: Youngone Lee <youngone.lee@accenture.com>
Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

2021-08-09 21:40 UTC, petermetz requested changes
@Leeyoungone Apologies I just noticed that the new packages that were added to the main branch in the meantime do not have the changes necessary (I found them by searching for `dist/types`)
Could you please update the PR to change these as well?

![dist-types-vs-lib-screenshot-from-2021-08-09 14-10-36](https://user-images.githubusercontent.com/1583231/128778031-68f60ff3-82ce-4435-a983-489a48a8baba.png)

2021-08-10 16:36 UTC, Leeyoungone commented
It's all good, thanks for pointing out the new files. I'm planning to change the carbon-accounting-app-dummy-infrastructure.ts file in PR 1145 to make things organized. The other ts files have been changed for this PR!

2021-08-12 18:01 UTC, petermetz approved these changes

2021-08-12 18:01 UTC, petermetz commented
@Leeyoungone Thank you for the updates, LGTM!

2021-08-12 20:02 UTC, takeutak approved these changes

2021-08-13 06:59 UTC, merged