Feat 1010 keychain azure handler endpoints
hyperledger/cactus pull request #1206
Opened 2021-08-11 14:31 UTC by Jeff-Ushry

2021-08-12 18:17 UTC, petermetz commented on packages/cactus-plugin-keychain-azure-kv/src/main/typescript/plugin-keychain-azure-kv.ts
> +  containerId(containerId: any);
@Jeff-Ushry I think you can delete these 3

2021-08-12 18:18 UTC, petermetz commented on packages/cactus-plugin-keychain-azure-kv/src/main/typescript/plugin-keychain-azure-kv.ts
> +  deleteKeychainId() {
@Jeff-Ushry This can probably also be deleted

2021-08-12 18:19 UTC, petermetz commented on packages/cactus-plugin-keychain-azure-kv/src/test/typescript/unit/webservice-tests.test.ts
> +    const apiClient = new KeychainAwsSmApi(config);
@Jeff-Ushry An import is missing that would pull in the DefaultApi class `as KeychainAwsSmApi`

2021-08-24 16:30 UTC, Leeyoungone commented
Fixes #1010

2021-09-03 19:45 UTC, Leeyoungone commented
Hello Peter! You requested changes for Jeff through the comments listed above but I can't seem to click a resolved request button or anything. I'm just gonna ping you for review here @petermetz

2021-09-12 03:52 UTC, petermetz commented
@Leeyoungone Sorry for the slow response. Do you remember if the parent PR with the core-api openapi spec changes were merged already or not? If not we have to mark this as dependent.

2021-09-13 14:18 UTC, Leeyoungone commented
@petermetz that pr has been merged! I think this is ready to go :)

2021-09-14 19:02 UTC, petermetz commented
> @petermetz that pr has been merged! I think this is ready to go :)

@Leeyoungone Okay, last step then is to point to that by replacing the relative paths like this, I found 10 occurrences:
`"../../../../cactus-core-api`

And after the rebase the core-api changes should disappear from this branch (because the same changes are now on `main` through the other PR).

This same chore has to be done for all the other keychain web-service PRs that are pending as well.

2021-09-15 04:13 UTC, Leeyoungone commented
@petermetz oof, I think I got the entirety of this issue now. So sorry for that earlier!!

2021-09-16 15:29 UTC, Leeyoungone commented
I've replaced the relative paths and rebased onto upstream/main, I think we're good to go!! @petermetz

2021-09-21 15:16 UTC, petermetz requested changes
@Leeyoungone `packages/cactus-core-api/src/main/json/openapi.json` has changes in it, those should to the a parent PR and then once that's merged+tagged those changes can be used by this PR

2022-04-01 03:30 UTC, petermetz approved these changes
@Jeff-Ushry @Leeyoungone LGTM, thank you!

2022-04-02 03:56 UTC, takeutak approved these changes

2022-04-03 18:06 UTC, merged