Iroha validator draft
hyperledger/cactus pull request #1327
Opened 2021-09-14 05:18 UTC by tkyonezu

Draft of Hyperledger Iroha Validator

2021-09-14 05:49 UTC, takeutak commented
Thanks for contributing your code!
As your proposal, there is a quite need for socketio-typed validators to Iroha developed by Python because it is necessary to expand the communication type and the diversity of development languages in order to increase the kinds of developers.

I created a new issue #1328 and I'm sure that your PR resolves this issue.
LGTM

2021-09-14 05:49 UTC, takeutak approved these changes

2021-09-14 19:20 UTC, petermetz requested changes
@tkyonezu Please rebase and squash the commits

2021-09-15 12:26 UTC, takeutak commented
@petermetz 
It seems that @tkyonezu has finished rebase and squash.
Would you mind if you review this PR again?

2021-09-18 20:24 UTC, petermetz commented
> @petermetz
> It seems that @tkyonezu has finished rebase and squash.
> Would you mind if you review this PR again?

@takeutak It still has multiple commits from what I can tell.

2021-09-22 14:49 UTC, takeutak commented
@petermetz Thanks for your response. I will contact @tkyonezu again.

By the way, if possible, could you mind if you solve this problem, @petermetz ?
@tkyonezu is a committer belonging to Soramitsu (not Fujitsu). So I have a little hesitant to ask him to solve this issue many times.

2021-09-22 15:31 UTC, takeutak commented
@petermetz Thanks for your response. I will contact @tkyonezu again.
Acccording to the commits <https://github.com/hyperledger/cactus/pull/1327/commits>, there are some unrelated commits as the following, so I think it is good to git revert these commits. Is this all right for you?
 - https://github.com/hyperledger/cactus/pull/1327/commits/e5d43207f69936336fdb501ba01854f358e8a483
 - https://github.com/hyperledger/cactus/pull/1327/commits/958bc7f53c3338848dac404729566569c9ea03bd
 - https://github.com/hyperledger/cactus/pull/1327/commits/7926f9ce81361eaa0fb744f46a789738f7677ab6

By the way, if possible, could you mind if you solve this GitHub problem, @petermetz ?
@tkyonezu is a committer belonging to Soramitsu (not Fujitsu). So I have a little hesitant to ask him to solve this issue many times.

2021-09-24 04:23 UTC, takeutak commented
@petermetz 
@tkyonezu executed git squash and there are one commit as the following:
https://github.com/hyperledger/cactus/pull/1327/commits

Would you mind approving this PR?

2021-09-24 20:45 UTC, petermetz approved these changes

2021-09-25 04:57 UTC, merged