Lint Fixes for Issue #1352
hyperledger/cactus pull request #1395
Opened 2021-10-01 19:53 UTC by rachel2code

Submitting fixes for Issue #1352, minus fix for ID 30. I am coordinating with another contributor before committing the fix for issue  ID 30.

2021-10-01 20:00 UTC, petermetz requested changes
@rachel2code 
1. Please fix the DCO (click the details button next to the check that was marked failed and it will provide example commands)
2. Please amend your git commit message to adhere to the formatting requirements  (we require a certain format/structure because of the release automation tooling we have in place that auto-generates change log entries for the releases). My recommended commit message below:
```sh
style: open source day batch #3

Fixes #1352 
```

2021-10-01 20:42 UTC, petermetz approved these changes
LGTM, thank you very much @rachel2code !

2021-10-01 22:16 UTC, petermetz commented
@rachel2code Oops, the compilation failed with these issues, the compiler provided some (at least semi) helpful messages, but do let me know if you need any help resolving these: https://github.com/hyperledger/cactus/pull/1395/checks?check_run_id=3771850580

2021-10-02 10:58 UTC, takeutak approved these changes

2021-11-25 23:44 UTC, merged