Fix: lint warning fix for any to unknown #1374
hyperledger/cactus pull request #1397
Opened 2021-10-01 21:05 UTC by yayoiukai2021

Lint fix for batch 25/26. + No.251 and No.240 (In the same file)

2021-10-01 22:34 UTC, petermetz requested changes

2021-10-01 22:34 UTC, petermetz commented on packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts
> +    const response: unknown = await this.getContainer().getArchive({
@yayoiukai2021 

I recommend simply omitting the explicit type declaration here in order to make the linter warning go away. Using unkown in this particular case just makes the compiler fail somewhere down the line.

```suggestion
const response = await this.getContainer().getArchive({
```

2021-10-01 22:35 UTC, petermetz commented
@yayoiukai2021 The other thing apart from my recommended change above is the DCO: If you click on the link labeled as "Details" next to the failing check (DCO) then it should give you specific instructions on how to fix it on the command line. If you encounter any trouble with it then feel free to ask for more help ;-)

2021-10-01 23:11 UTC, petermetz approved these changes
@yayoiukai2021 LGTM, thank you very much!

2021-10-02 10:59 UTC, takeutak approved these changes

2021-10-04 17:40 UTC, petermetz requested changes
@yayoiukai2021 You will also need to import the `Stream` type in order to make my other suggestion work with something like this:

```typescript
import { Stream } from "stream";
```

2021-10-04 17:40 UTC, petermetz commented on packages/cactus-test-tooling/src/main/typescript/quorum/quorum-test-ledger.ts
> +      );
@yayoiukai2021 I'd fix the compiler error like this:

```suggestion
  private pullContainerImage(containerNameAndTag: string): Promise<unknown[]> {
    return new Promise((resolve, reject) => {
      const docker = new Docker();
      docker.pull(containerNameAndTag, (pullError: unknown, stream: Stream) => {
        if (pullError) {
          reject(pullError);
        } else {
          docker.modem.followProgress(
            stream,
            (progressError: unknown, output: unknown[]) => {
              if (progressError) {
                reject(progressError);
              } else {
                resolve(output);
              }
            },
          );
        }
      });
    });
  }
```

2022-04-01 03:34 UTC, petermetz commented
Closing due to inactivity, feel free to reopen as needed and then we can continue the review.

2022-04-01 03:34 UTC, closed without merging