deprecate rotateEncryptionKeys method #1108
hyperledger/cactus pull request #1402
Opened 2021-10-01 23:09 UTC by epartakki

refactor(keychain): deprecate rotateEncryptionKeys method #1108

Found 6 locations of the method:
This pull request removes the method from 6/6 locations

2021-10-01 23:17 UTC, petermetz requested changes
@epartakki The squash was successful, but the commit message needs to be amended for the commit lint check in order to be similar to how the PR description is (GitHub does not automatically sync the two unfortunately)

```sh
refactor(keychain): deprecate rotateEncryptionKeys method #1108

Fixes #1108 

Found 6 locations of the method:
This pull request removes the method from 6/6 locations
```

You can amend the commit message with something like

```sh
git commit --amend --signoff
```

```sh
git push --force-with-lease
```

2021-10-01 23:20 UTC, epartakki commented
@petermetz I did that Peter, did it make a difference? I am not sure I understand what the issue is

2021-10-01 23:47 UTC, petermetz approved these changes
@epartakki LGTM, thank you !

2021-10-02 11:02 UTC, takeutak approved these changes

2021-10-02 19:18 UTC, merged