Lint warning fixes for 34, 37, 38, 39, 40
hyperledger/cactus pull request #1437
Opened 2021-10-04 23:22 UTC by cotikor

2021-10-05 01:06 UTC, takeutak approved these changes

2021-10-06 18:14 UTC, petermetz commented
@cotikor Which issue is this for? (I assume it's one of the good first issue labeled ones we prepared for GHC OSD, right?)

2021-11-01 20:43 UTC, petermetz requested changes
@cotikor Please fix the DCO warning: there's a guide on how to do it if you click 'details' next to the failing check.
Also: Please rebase  + squash onto the latest upstream main to resolve the conflicts, let me know if you need any help with git mechanics!

2021-11-01 20:43 UTC, petermetz commented on packages/cactus-cmd-api-server/src/main/typescript/config/config-service.ts
> +  default: null
@cotikor What is the purpose of this new property on this type?

2022-04-01 02:10 UTC, petermetz commented
Closing due to inactivity, feel free to reopen as needed.

2022-04-01 02:10 UTC, closed without merging