test: jestify besu-erc20 refund endpoint invalid time test
hyperledger/cactus pull request #1545
Opened 2021-11-18 04:00 UTC by awadhana

Migrated test from Tap to Jest.

File Path:
packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/refund-endpoint-invalid-time.test.ts

This is a PARTIAL resolution to #238 and other half of test file path:
packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/refund-endpoint.test.ts

Signed-off-by: awadhana <awadhana0825@gmail.com>

2021-11-22 15:58 UTC, takeutak approved these changes

2021-11-23 18:57 UTC, petermetz requested changes
@awadhana LGTM but before merging please make sure the PR description and the git commit are updated to not resolve the main jest issue.

2021-12-01 16:14 UTC, awadhana commented
> @awadhana LGTM but before merging please make sure the PR description and the git commit are updated to not resolve the main jest issue.

Done :)

2021-12-05 04:04 UTC, petermetz approved these changes
@awadhana Great, thank you!

2021-12-05 16:16 UTC, merged