test: jestify deploy-contract-from-json-xdai test
hyperledger/cactus pull request #1546
Opened 2021-11-18 19:58 UTC by awadhana

Migrated test from Tap to Jest.

File Path:
packages/cactus-plugin-ledger-connector-xdai/src/test/typescript/integration/deploy-contract-from-json-xdai.test.ts

This is a PARTIAL resolution to issue #238 

Signed-off-by: awadhana <awadhana0825@gmail.com>

2021-11-22 16:01 UTC, takeutak approved these changes

2021-11-23 19:00 UTC, petermetz requested changes
@awadhana LGTM but before merging please make sure the PR description and the git commit are updated to not resolve the main jest issue.

2021-12-04 03:40 UTC, awadhana commented
> @awadhana LGTM but before merging please make sure the PR description and the git commit are updated to not resolve the main jest issue.

@petermetz  Done :)

2021-12-07 02:07 UTC, petermetz approved these changes
@awadhana Thank you, LGTM!

2021-12-07 22:28 UTC, merged