test: jestify plugin-import-with-npm-install test
hyperledger/cactus pull request #1678
Opened 2021-12-26 22:55 UTC by awadhana

Migrated test from Tap to Jest.

File Path:
packages/cactus-test-cmd-api-server/src/test/typescript
/integration/plugin-import-with-npm-install.test.ts

This is a PARTIAL resolution to issue #238

Signed-off-by: awadhana awadhana0825@gmail.com

2021-12-26 23:06 UTC, awadhana commented
Similar duplicate PR

2021-12-27 23:51 UTC, petermetz requested changes

2021-12-27 23:51 UTC, petermetz commented on packages/cactus-test-cmd-api-server/src/test/typescript/integration/plugin-import-with-npm-install.test.ts
> +    await expect(startResponse).toBeTruthy();
@awadhana Same suggestion here as I made in the other PR: use the `.resolves` syntax (exact details in the other PR comment I made)

2022-01-26 16:11 UTC, awadhana commented
Duplicate PR, so closing :)

2022-01-26 16:12 UTC, closed without merging