style: 2021-09-20 linter warnings batch 23/26
hyperledger/cactus pull request #1779
Opened 2022-01-14 07:48 UTC by zondervancalvez

fixes: #1371

2022-01-14 22:27 UTC, petermetz approved these changes
@zondervancalvez Thank you very much, LGTM!

2022-01-19 01:42 UTC, petermetz approved these changes
@zondervancalvez LGTM, thank you!

2022-01-20 19:08 UTC, takeutak approved these changes

2022-01-21 22:33 UTC, petermetz requested changes
@zondervancalvez Sorry, I just realized that the commit message you have is way too generic.

Could you make the commit message mirror the issue title instead?
`style: 2021-09-20 linter warnings batch 23/26`

And also include the `Fixes #???` syntax in the commit message body so that we can trace it back later directly from the git logs instead of via the github PR description only.

2022-02-09 06:37 UTC, closed without merging