fix(security): address CVE-2021-23337
hyperledger/cactus pull request #1820
Opened 2022-01-28 07:55 UTC by aldousalvarez

Fixes #1778

Signed-off-by: aldousalvarez <aldousss.alvarez@gmail.com>

2022-01-29 02:19 UTC, petermetz requested changes
@aldousalvarez Please resolve the conflicts and then the CI should run and we'll see if the changes work or not. I am a bit suspicious there though because you only updated the dependencies but not the imports in the code nor the usage of the methods (which may be fine if it's a drop-in replacement for all the methods that we use but I don't know that for sure either from the top of my head)

2022-02-25 07:59 UTC, petermetz commented
@aldousalvarez @zondervancalvez If this depends on https://github.com/hyperledger/cactus/pull/1816 (or the other way around) then please make sure to declare that dependency in the PR description so that the robot enforces the merge order correctly.

2022-03-11 02:27 UTC, petermetz requested changes
@aldousalvarez Please make sure to rebase onto the parent PR once the conflicts are fixed there. Then also make sure that the tests here are also  passing.

2022-03-30 21:42 UTC, petermetz commented
@aldousalvarez Please add a commit to this branch that updates the resolutions in the root package.json to specify >=4.17.21 as the lodash version

E.g., instead of this:

```json
  "resolutions": {
    "ansi-html": ">0.0.8",
    "glob-parent": "5.1.2",
    "lodash": "4.17.20",
    "minimist": ">=1.2.6",
    "node-forge": ">=1.3.0",
    "underscore": "1.13.2"
  }
```

We need this:

```json
  "resolutions": {
    "ansi-html": ">0.0.8",
    "glob-parent": "5.1.2",
    "lodash": ">=4.17.21",
    "minimist": ">=1.2.6",
    "node-forge": ">=1.3.0",
    "underscore": "1.13.2"
  }
```

Once you add that commit to this branch, the PR can be reopened and merged.

2022-03-30 21:43 UTC, petermetz reviewed
^^ See my above request

2022-03-31 07:21 UTC, aldousalvarez commented
Hello @petermetz I have committed the changes that you requested on to this branch aldousalvarez/issue1778. Will the PR be opened again? Thank you.

2022-04-02 02:06 UTC, petermetz approved these changes
@aldousalvarez Yes, I reopened it just now. LGTM

2022-04-02 03:55 UTC, takeutak approved these changes

2022-04-02 23:15 UTC, merged