test: jestify plugin-keychain-memory test
hyperledger/cactus pull request #1835
Opened 2022-02-03 14:25 UTC by awadhana

Migrated test from Tap to Jest.

File Path:
packages/cactus-plugin-keychain-memory/src/
test/typescript/unit/plugin-keychain-memory.test.ts

This is a PARTIAL resolution to issue https://github.com/hyperledger/cactus/issues/238

Signed-off-by: awadhana <awadhana2021@gmail.com>

2022-02-07 17:59 UTC, petermetz requested changes

2022-02-07 17:59 UTC, petermetz commented on packages/cactus-plugin-keychain-memory/src/test/typescript/unit/plugin-keychain-memory.test.ts
> +    ).toThrow;
@awadhana You need to call the function instead of just referencing it.

2022-02-07 17:59 UTC, petermetz commented on packages/cactus-plugin-keychain-memory/src/test/typescript/unit/plugin-keychain-memory.test.ts
> +    expect(plugin.get(key1)).not.toResolve();
@awadhana Need to `await` this one so that there is no race with the other assertions

2022-02-17 00:47 UTC, petermetz requested changes

2022-02-17 00:47 UTC, petermetz commented on packages/cactus-plugin-keychain-memory/src/test/typescript/unit/plugin-keychain-memory.test.ts
> +    await expect(hasAfterDelete1).not.toBeTruthy();
@awadhana This line did not need the await, `toBeTruthy()` is synchronous. I just meant the other one that asserts that the promise resolves.

`expect(plugin.get(key1)).not.toResolve();`

2022-03-21 16:44 UTC, takeutak approved these changes

2022-11-23 05:00 UTC, jagpreetsinghsasan approved these changes

2022-11-25 21:49 UTC, merged