Cactus test plugin htlc eth besu erc20/withdraw endpoint invalid
hyperledger/cactus pull request #1889
Opened 2022-03-02 19:07 UTC by awadhana

Migrated test from Tap to Jest.

File Path:
packages/cactus-test-plugin-htlc-eth-besu-erc20/src/test/typescript/integration/plugin-htlc-eth-besu-erc20/withdraw-endpoint-invalid-id.test.ts

This is a PARTIAL resolution to issue https://github.com/hyperledger/cactus/issues/238

Signed-off-by: awadhana <awadhana2021@gmail.com>

2022-03-02 19:12 UTC, awadhana commented
@petermetz , this is the other half that you were asking about in #1591 ! 

This belongs with the other PR, https://github.com/hyperledger/cactus/pull/1591.

2022-03-02 22:40 UTC, petermetz requested changes
> @petermetz , this is the other half that you were asking about in #1591 ! 

This belongs with the other PR, https://github.com/hyperledger/cactus/pull/1591.  

@awadhana Looking at my comment from back then[1], here's what you need to do:
1. Add this file as part of the other PR (#1591)
2. Close this PR down, it's not needed.


[1] 
> @awadhana If this is one of those test cases that you broke into two as part of the Jest migration then please > also add in the other test file as part of the PR (if not already merged in another PR). Otherwise we would  leave certain coverage missing if we merged this as-is.

2022-03-21 16:43 UTC, takeutak approved these changes

2022-11-26 20:13 UTC, petermetz commented
Closing as redundant with: https://github.com/hyperledger/cactus/pull/1591

2022-11-26 20:13 UTC, closed without merging