fixing issue #1613 with typos of diagram
hyperledger/cactus pull request #1954
Opened 2022-03-30 00:59 UTC by epartakki

2022-03-30 01:17 UTC, takeutak approved these changes

2022-03-30 02:08 UTC, petermetz requested changes
@epartakki Thank you very much! The diff LGTM, but we have to make sure that all the checks are passing as well.
Right now your commit message is not conformant to some syntax requirements that we have in place in order to achieve a higher degree of automation compared to what's usually possible.

TLDR: As a first step, change your commit message to something like this:
```
docs: fix diagram typo in connector README files

Fixes #1613

Signed-off-by: $FIRST_NAME $LAST_NAME <$EMAIL_ADDRESS>
```
Substitute the $FIRST_NAME $LAST_NAME <$EMAIL_ADDRESS> part with your data of course, so that it looks similar to mine, but with your details:
`Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>`

You'll need to amend your commit and then force push it (with lease). If you need help with getting this done in git just let me know and also invite me as a collaborator to your fork to make things easier in case I need to step in.

2022-03-30 13:49 UTC, epartakki commented
@petermetz Thank you! I have amended and pushed with lease, but how do I replace my pull request?

2022-03-30 17:42 UTC, closed without merging

2022-04-09 05:59 UTC, petermetz commented
> @petermetz Thank you! I have amended and pushed with lease, but how do I replace my pull request?

@epartakki Sorry for the slow response here! Just wanted to drop by here to say for the future: Please try to avoid opening another pull request with the same diff a second time. It doubles the effort on reviewing - it did not make much of a difference in this particular case, but if it was a PR that takes 2 hours to review then it's a much harder pill to swallow. It's not a big deal or anything I just wanted to mention it for next time.