test(connector-iroha): tested previously skipped test
hyperledger/cactus pull request #1968
Opened 2022-04-12 21:45 UTC by Leeyoungone

All I did was change from `test.skip` to just `test` and it turns out that the test works just fine. So for I've ran the test 20 times and it has passed every single time. This issue is a "fix" to #1957 ?

Signed-off-by: Youngone Lee <youngone.lee@accenture.com>

2022-04-13 13:10 UTC, takeutak approved these changes

2022-04-19 18:38 UTC, petermetz requested changes
> All I did was change from `test.skip` to just `test` and it turns out that the test works just fine. So for I've ran the test 20 times and it has passed every single time. This issue is a "fix" to #1957 ?

> Signed-off-by: Youngone Lee <youngone.lee@accenture.com> 

@Leeyoungone Please put this also in the commit message and also the information I wrote in the issue comment so that people looking at the git log see the full context. Once that's done it's LGTM

2022-04-20 02:51 UTC, Leeyoungone commented
@petermetz Sounds good! Just fixed it :))

2022-05-09 21:54 UTC, petermetz approved these changes
@Leeyoungone LGTM, thank you!
Note to my future self: if this gets flaky again on the CI, we need to start skipping it again.
Note to Wen: Please remove  commented code that you no longer need ;-)

2022-05-10 21:29 UTC, merged