Cross-Site Scripting attack (XSS).
hyperledger/cactus pull request #1973
Opened 2022-04-14 05:32 UTC by bhaskarvilles

Unsanitized input from an HTTP parameter flows into send, where it is used to render an HTML page returned to the user. This may result in a Cross-Site Scripting attack (XSS).

Signed-off-by: Bhaskar <dev@bhaskar.email>

2022-04-15 01:41 UTC, izuru0 reviewed
@bhaskarvilles User input `req.params.id` is fed to `escapeHtml` before `res.send` sees it. Are there cases that output from `escapeHtml` can still be harmful?

2022-04-15 07:11 UTC, bhaskarvilles commented
> @bhaskarvilles User input `req.params.id` is fed to `escapeHtml` before `res.send` sees it. Are there cases that output from `escapeHtml` can still be harmful?

Yes, in some cases it happens, So we have to  Sanitize data input in an HTTP request before reflecting it back, ensuring all data is validated, filtered or escaped before echoing anything back to the user, such as the values of query parameters during searches. And also convert special characters into their respective HTML or URL encoded equivalents.

2022-04-18 23:43 UTC, izuru0 approved these changes
@bhaskarvilles ok, thanks!

LGTM

I've approved it, but do you mind if I asked for an example or url to docs including an example describing the risk you mentioned?

2022-04-19 16:17 UTC, bhaskarvilles commented
> @bhaskarvilles ok, thanks!
> 
> LGTM
> 
> I've approved it, but do you mind if I asked for an example or url to docs including an example describing the risk you mentioned?

You can Find [here](https://cwe.mitre.org/data/definitions/79.html)

2022-04-21 20:12 UTC, bhaskarvilles commented
@izuru0 
I think you haven't merged my pr and not referenced in any commit if merged ?

2022-04-25 22:22 UTC, petermetz approved these changes
@bhaskarvilles LGTM, thank you!

2022-04-26 00:52 UTC, petermetz requested changes
@bhaskarvilles Please squash the commits into a single one with an interactive rebase. Let me know if you need help and if you do make sure to invite me to your fork as a collaborator.

2022-05-01 03:44 UTC, bhaskarvilles commented
> @bhaskarvilles Please squash the commits into a single one with an interactive rebase. Let me know if you need help and if you do make sure to invite me to your fork as a collaborator.

I've invited you as collaborators, please squash and commit changes.

2022-05-02 17:24 UTC, petermetz approved these changes
@bhaskarvilles LGTM, thank you!

FYI: I fixed the commits for you, please double check that you are also happy with them as-is before we merge.

2022-05-02 20:53 UTC, merged

2022-05-03 19:45 UTC, bhaskarvilles commented
> @bhaskarvilles LGTM, thank you!
> 
> FYI: I fixed the commits for you, please double check that you are also happy with them as-is before we merge.

I'm happy to see my contributions publicly, always ❤️ Open-Source. Thank you for helping me in squashing @petermetz