test: jestify v21.4.1 invoke contract test
hyperledger/cactus pull request #2043
Opened 2022-05-24 12:57 UTC by Leeyoungone

Migrate Tap to Jest

File Path:
packages/cactus-plugin-ledger-connector-quorum/
src/test/typescript/
integration/plugin-ledger-connector-quorum/
deploy-contract/
v21.4.1-invoke-contract.test.ts

This is a PARTIAL resolution to issue #238

Signed-off-by: Youngone Lee <youngone.lee@accenture.com>

2022-05-25 02:21 UTC, takeutak approved these changes

2022-05-25 23:10 UTC, petermetz requested changes

2022-05-25 23:10 UTC, petermetz commented on packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-invoke-contract.test.ts
> +  // test("Quorum Ledger Connector Plugin", async (t: Test) => {
@Leeyoungone No commented code unless you need it for something specific please :-)

2022-05-25 23:10 UTC, petermetz commented on packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-invoke-contract.test.ts
> +    // t.equals(parseInt(balance, 10), 10e9, "Balance of test account is OK");
@Leeyoungone No commented code unless you need it for something specific please :-)

2022-05-25 23:10 UTC, petermetz commented on packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-invoke-contract.test.ts
> +      // test("deploys contract via .json file", async (t2: Test) => {
@Leeyoungone No commented code unless you need it for something specific please :-)

2022-05-25 23:10 UTC, petermetz commented on packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-invoke-contract.test.ts
> +      // t2.true(
@Leeyoungone No commented code unless you need it for something specific please :-)

2022-05-25 23:10 UTC, petermetz commented on packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-invoke-contract.test.ts
> +    // test("invoke Web3SigningCredentialType.GETHKEYCHAINPASSWORD", async (t2: Test) => {
@Leeyoungone No commented code unless you need it for something specific please :-)

2022-05-31 18:56 UTC, Leeyoungone commented on packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-invoke-contract.test.ts
> +        // t2.ifError(setNameOutInvalid.transactionReceipt);
got it! so sorry for the extra effort you had to put into this !!

2022-07-13 23:07 UTC, petermetz commented on packages/cactus-plugin-ledger-connector-quorum/src/test/typescript/integration/plugin-ledger-connector-quorum/deploy-contract/v21.4.1-invoke-contract.test.ts
> +        // t2.ifError(setNameOutInvalid.transactionReceipt);
> got it! so sorry for the extra effort you had to put into this !!

@Leeyoungone No worries, thank you for diligently addressing all the nit picks of mine. :-)

2022-07-13 23:08 UTC, petermetz approved these changes
@Leeyoungone LGTM, thank you!

2022-07-18 13:31 UTC, merged