docs(build): add text build steps for Linux, Mac and Windows
hyperledger/cactus pull request #2072
Opened 2022-06-10 02:13 UTC by AbhinavMir

Issue: #1963

Signed-off-by: Abhinav Srivastava <atg271@gmail.com>

2022-06-13 22:06 UTC, petermetz requested changes
@AbhinavMir 

1. apt is only there on Debian and it's downstream distros so I would somehow make it clear and then in separate sections you could detail the steps for Win and Mac so that people don't get confused.
2. Instead of npm, please use yarn where possible
3. Do not install the `nodejs` package via apt (not even on the Debian distros). We strongly encourage/prefer the use of the node version manager tool (nvm)
4. Let's push people towards JDK 11 instead of JDK 8

2022-06-13 23:06 UTC, AbhinavMir commented
have addressed 2,3,4 in latest commit. I think for 1, we can create a new issue to create separate build instructions on Windows and Mac.

2022-07-11 05:07 UTC, jagpreetsinghsasan requested changes

2022-07-11 05:07 UTC, jagpreetsinghsasan commented on BUILD.md
> +### Cactus BUILD instruction
I believe saying Hyperledger Cactus (instead of just Cactus) here is better.

2022-07-11 05:07 UTC, jagpreetsinghsasan commented on BUILD.md
> +sudo docker run hello-world
After this line, reference can also be given to use docker without sudo, as mentioned here, https://docs.docker.com/engine/install/linux-postinstall/

2022-07-11 05:07 UTC, jagpreetsinghsasan commented on BUILD.md
> +You can download and install VS Code from [here](https://code.visualstudio.com/download). It is suggested to install the git-graph and Docker plugins.
Here, we can also mention the `npm-scripts` plugin as well (https://marketplace.visualstudio.com/items?itemName=traBpUkciP.vscode-npm-scripts)

2022-07-11 05:07 UTC, jagpreetsinghsasan commented on BUILD.md
> +yarn add
We can specify the `npm run install-yarn` prior to`yarn add` (yarn-add isn't required)

2022-09-25 06:27 UTC, closed without merging