style: remediate linter errors in examples and test-tooling
hyperledger/cactus pull request #2076
Opened 2022-06-14 17:39 UTC by alec-p-hong

Some of the fixes were updated by Peter after Alec's internship has
come to an end before he could finish the requested changes.

Signed-off-by: Alec Phong <alecphong@gmail.com>
Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>

Co-authored-by: Peter Somogyvari <peter.somogyvari@accenture.com>

Partial solution #1375

2022-06-15 06:31 UTC, jagpreetsinghsasan approved these changes
LGTM, the only thing which can be better is the PR message and the commit message itself.
For the PR message you can write something like [this](https://github.com/hyperledger/cactus/pull/659) and for the commit message you can write something like [this](https://github.com/hyperledger/cactus/pull/659/commits/b9fe98b0add352b0d68a5fe446d3fa000603d21c)

2022-06-16 00:02 UTC, takeutak approved these changes

2022-07-18 01:55 UTC, petermetz requested changes
@alec-p-hong +1 on what Jagpreet was saying and the same from my side => https://github.com/hyperledger/cactus/pull/2080#pullrequestreview-1041221189

2022-12-01 18:57 UTC, petermetz approved these changes
LGTM

2022-12-01 21:28 UTC, merged