fix(index.ts, emissionsRecordCOntract.ts, get-allowance-endpoint.ts): fixed lint errors on multiple files
hyperledger/cactus pull request #2079
Opened 2022-06-15 20:14 UTC by alec-p-hong

Primary Change
--------------

1. Fixed lint errors on index.ts (line 578, col 25), emissionsRecordContract.ts (line 40, col 3; line 138, col 3; line 146, col 3), and endpoint.ts (line 58, col 33) 
2. In order to fix changes from any to unknown, had to change the output path to directed types: (Changed OASPath return type from any object to "typeof OAS.paths["/api/v1/plugins/@hyperledger/cactus-example-carbon-accounting-backend/dao-token/get-allowance"]"
------------------------------------------------------------
Partial Fix to #1366

2022-06-16 00:03 UTC, takeutak approved these changes

2022-06-16 07:19 UTC, jagpreetsinghsasan approved these changes
LGTM

2022-07-18 01:54 UTC, petermetz requested changes
@alec-p-hong Same as here: https://github.com/hyperledger/cactus/pull/2080#pullrequestreview-1041221189

2022-12-01 23:23 UTC, petermetz commented
Closing because after resolving the merge conflicts on it it became equivalent to the main branch (a previous PR made the same changes as this one)

2022-12-01 23:23 UTC, closed without merging