fix(examples): fixed multiple lint errors in examples folder also changed the return types for more functions.
hyperledger/cactus pull request #2080
Opened 2022-06-15 22:34 UTC by alec-p-hong

Primary Change

1. Fixed lint errors on utility-emissions-channel/enroll-admin-v1-endpoint.ts (line 54, col 25), insert-bamboo-harvest-endpoint.ts (line 78, col 3), insert-bookshelf-endpoint.ts (line 59, col 3), insert-shipment-endpoint.ts (line 69, col 3), list-bamboo-harvest-endpoint.ts (line 38, col 3; line 58, col 3; ), list-bookshelf-endpoint.ts (line 56, col 3), and list-shipment-endpoint.ts (line 40, col 3)
2. In order to fix changes from any to unknown, had to change the output path to directed types: (Changed OASPath return type from any object to "typeof OAS.paths["/api/v1/plugins/@hyperledger/cactus-example-carbon-accounting-backend/dao-token/get-allowance"]"
3. Removed import statements that were never used in the file (import e)
Partial Fix to #1366

2022-06-16 00:03 UTC, takeutak approved these changes

2022-06-16 07:20 UTC, jagpreetsinghsasan approved these changes
LGTM

2022-07-18 01:52 UTC, petermetz requested changes
@alec-p-hong Please squash the commits into a single one and then list the changes made in the commit message there (so that the information is not lost completely when you squash )

Also make sure to have the `Fixes #????` declaration in the commit message if this is related to a specific issue in the tracker. That way it automatically closes down the issue once the PR gets merged.

The PR description looks good BTW, you just need to make sure that the one commit after the squash is in sync with that at least. GitHub (the platform) and git (the open source tool for version control) are not fully aware of each other in this sense so when you update the PR description here on the website it doesn't automagically change the commit messages with it.

2022-12-02 02:28 UTC, petermetz approved these changes
I made the requested changes myself. LGTM

2022-12-02 06:20 UTC, merged