fix: compile errors in the electricity-trade example
hyperledger/cactus pull request #2095
Opened 2022-06-22 16:41 UTC by janvinsha

This fix allows the cactus repository to configure without errors when `npm run configure` is run in the cactus root directory
It enables various examples like the electricity-trade to work
Signed-off-by: Jande Vincent [janvinsha@gmail.com](url)

2022-06-23 02:03 UTC, takeutak approved these changes

2022-06-23 02:04 UTC, takeutak commented
@janvinsha Thanks for your contribution!

2022-06-23 06:25 UTC, jagpreetsinghsasan approved these changes
LGTM. Thankyou for the contribution.

2022-07-16 08:56 UTC, petermetz requested changes
@janvinsha Please squash the commits into a single one and then we are good to go AFAICT => LGTM

2022-07-20 19:15 UTC, ryjones commented
@petermetz I fixed this

2022-07-21 04:47 UTC, petermetz reviewed
@janvinsha Is this needed though? I'm pretty sure the configure script works without it because otherwise the CI build+ tests would be broken.

2022-12-01 23:26 UTC, petermetz commented
Closing due to inactivity + I don't think we need this because the build is not broken on the main branch.

2022-12-01 23:26 UTC, closed without merging