feat(sawtooth-ledger): add single sawtooth test ledger image
hyperledger/cactus pull request #2110
Opened 2022-07-01 18:27 UTC by outSH

feat(sawtooth-ledger): add single sawtooth test ledger image

- Enclose starting sawtooth ledger into single container that will fetch and run the entire setup.
- Remove reduntant files, update the readme.
- Add SawtoothTestLedger class to simplify setting the test ledger in jest tests.
- Refactor electricity-trade to generate usage without sawtooth shell patching.
- Refactor electricity-trade to use new sawtooth ledger container and wait until it's healthy.

Closes: https://github.com/hyperledger/cactus/issues/2108

Depends on: https://github.com/hyperledger/cactus/pull/2030

Signed-off-by: Michal Bajer <michal.bajer@fujitsu.com>

2022-07-06 12:58 UTC, jagpreetsinghsasan approved these changes
LGTM

2022-07-20 10:28 UTC, izuru0 approved these changes
LGTM

2022-07-21 01:03 UTC, petermetz requested changes
@outSH 

1. FYI: The official image is now published here: https://github.com/orgs/hyperledger/packages/container/package/cactus-sawtooth-all-in-one
2. Could you please also add the publis CI yaml file in the .github/workflows dir next to the rest of the container publishing files? Easiest is to just copy paste one of the existing ones and then you mostly just tell it where the dockerfile is and how to build it (please be sure to use a docker build command in that yaml file that works from the project root directory without having to change directories inwards first.

2022-08-10 08:21 UTC, outSH commented on packages/cactus-test-tooling/src/main/typescript/sawtooth/sawtooth-test-ledger.ts
> +  containerImageVersion: "dev1",
Done

2022-08-10 08:22 UTC, outSH commented on packages/cactus-test-tooling/src/main/typescript/sawtooth/sawtooth-test-ledger.ts
> +  containerImageName: "ghcr.io/outsh/cactus-sawtooth-all-in-one",
Done

2022-08-10 08:23 UTC, outSH commented
>     1. FYI: The official image is now published here: https://github.com/orgs/hyperledger/packages/container/package/cactus-sawtooth-all-in-one

Thanks!

>     2. Could you please also add the publis CI yaml file in the .github/workflows dir next to the rest of the container publishing files? Easiest is to just copy paste one of the existing ones and then you mostly just tell it where the dockerfile is and how to build it (please be sure to use a docker build command in that yaml file that works from the project root directory without having to change directories inwards first.

Oh, forgot about that, thanks for reminder - done :)

2022-08-24 17:54 UTC, petermetz approved these changes
> Oh, forgot about that, thanks for reminder - done :)
 
@outSH My pleasure, thank you for making the updates! LGTM!

2022-08-25 23:47 UTC, merged