feat(iroha2-ledger): add Iroha V2 test ledger image and setup class
hyperledger/cactus pull request #2140
Opened 2022-08-03 11:13 UTC by outSH

- Add a new test image for Iroha V2 (iroha2-all-in-one). It start a test ledger in single container,
  and also contains a proxy script for running iroha_client_cli.
- Add the new image to the CI.
- Add a new class for starting and interacting with Iroha V2 test ledger
  from typescript test - Iroha2TestLedger.
- Add test for test setup class to ensure basic functions are working correctly.

Relates to #2138

Signed-off-by: Michal Bajer <michal.bajer@fujitsu.com>

2022-08-03 11:15 UTC, outSH commented on .github/workflows/iroha2-all-in-one-publish.yaml
> +  IMAGE_NAME: cactus-iroha2-all-in-one
@petermetz Please upload this image to main ghcr so I can replace references in the commit :)

2022-08-24 20:28 UTC, petermetz requested changes
> @petermetz @jagpreetsinghsasan @izuru0 Please upload this image to main ghcr so I can replace references in the commit :) 

@outSH Sorry for the slow response again! I've just pushed the new image to the official repo, please use this tag in the code: `ghcr.io/hyperledger/cactus-iroha2-all-in-one:2022-08-24-b4d59707b`

2022-09-02 12:20 UTC, outSH commented on tools/docker/iroha2-all-in-one/README.md
> +> Excute from `tools/docker/iroha2-all-in-one` or adjust the paths accordingly.
@petermetz Sure thing - done. I've also changed the references from my ghcr to hyperledger ghcr image.

2022-10-14 14:13 UTC, outSH commented
@petermetz I've updated the `Dockerfile` to use specific image instead of generic Iroha2 LTS tag that broke recently. Please upload this image once again, so I can update it through the tests.

2022-10-18 20:05 UTC, petermetz commented
> @petermetz I've updated the `Dockerfile` to use specific image instead of generic Iroha2 LTS tag that broke recently. Please upload this image once again, so I can update it through the tests.

@outSH I published the new image as `ghcr.io/hyperledger/cactus-iroha2-all-in-one:2022-10-18-06770b6c`

2022-10-18 20:06 UTC, petermetz requested changes
@outSH Please pass the ball back with a "re-request review" once the image was updated and then we can merge!

`ghcr.io/hyperledger/cactus-iroha2-all-in-one:2022-10-18-06770b6c`

2022-10-31 21:38 UTC, petermetz approved these changes
@outSH Thanks, LGTM

2022-11-11 03:26 UTC, takeutak approved these changes

2022-11-14 07:14 UTC, merged