docs(odap-plugin): update odap plugin doc
hyperledger/cactus pull request #2192
Opened 2022-11-08 17:27 UTC by AndreAugusto11

Following the merge of  #2154 this is the update of the README file

Signed-off-by: André Augusto <andre.augusto@tecnico.ulisboa.pt>

2022-11-10 19:52 UTC, takeutak approved these changes

2022-11-15 19:43 UTC, petermetz approved these changes
@AndreAugusto11 Thank you very much! LGTM!

2022-11-15 19:45 UTC, petermetz requested changes
@AndreAugusto11 Sorry, one more thing before we merge. Please describe in the  commit message and also the commit subject and also in the PR description the change that is being made.

The "updated X file" type of commit messages are ambiguous to 99% of all other changes that we make to the source code (imagine trying to find your own changes if everyone just said to everything "updated x" in their commits ;-))

2022-11-17 21:22 UTC, petermetz approved these changes
@AndreAugusto11 LGTM, thank you for the updates!

2022-11-20 08:45 UTC, merged