fix(plugin-ledger-connector-iroha): running dockerfile locally
hyperledger/cactus pull request #2207
Opened 2022-11-16 05:40 UTC by jagpreetsinghsasan

## Commit to be reviewed
----------------------------------

fix(plugin-ledger-connector-iroha): running dockerfile locally  
    
    Primary Changes
    ---------------
    1. Updated iroha package.json to include a missing dependency
    2. Updated Dockerfile to include new api-server image and
       used yarn to install the iroha package
    3. Updated README.md to include the newly changes to both
       the api-server as well as iroha connector plugin
    4. Updated cmd-api-server README.md to include similar
       changes

Fixes #1874

Signed-off-by: jagpreetsinghsasan <jagpreet.singh.sasan@accenture.com>

2022-11-16 06:02 UTC, jagpreetsinghsasan commented
For testing of this PR, I have created a sample npm package (will delete it as soon as this gets merged, not wanna pollute the npm registry with test packages).

To test this PR, please perform the following steps
1. Update the contents of packages/cactus-plugin-ledger-connector-iroha/Dockerfile to
```
FROM ghcr.io/hyperledger/cactus-cmd-api-server:2022-11-14-6ff6aac
RUN npm install -g yarn@1.22.17

ENV NODE_ENV=production
ARG NPM_PKG_VERSION=latest

RUN yarn add jagirohatestdep@${NPM_PKG_VERSION} --production --ignore-engines
```

2. Create the docker image using
```
DOCKER_BUILDKIT=1 docker build -f ./packages/cactus-plugin-ledger-connector-iroha/Dockerfile . -t cplcb
```

3. Run the iroha connector (in this case, one need to run `jagirohatestdep` because the new iroha npm module needs to be updated) using the command
```
docker run \
  --rm \
  --publish 3000:3000 \
  --publish 4000:4000 \
  --publish 5000:5000 \
  --env AUTHORIZATION_CONFIG_JSON="{}"\
  --env AUTHORIZATION_PROTOCOL=NONE \
  --env GRPC_TLS_ENABLED=false \
  --env PLUGINS='[{"packageName": "jagirohatestdep", "type": "org.hyperledger.cactus.plugin_import_type.LOCAL", "action": "org.hyperledger.cactus.plugin_import_action.INSTALL",  "options": {"rpcApiHttpHost": "http://localhost:8545", "rpcToriiPortHost": "http://localhost:8545", "instanceId": "some-unique-iroha-connector-instance-id"}}]' \
  cplcb:latest
  ```

2022-11-17 20:33 UTC, takeutak approved these changes

2022-11-17 21:47 UTC, petermetz requested changes
@jagpreetsinghsasan Please fix the merge conflicts and then pass it back for review!

cc: @outSH

2022-11-19 01:23 UTC, petermetz approved these changes
@jagpreetsinghsasan LGTM, thank you very much for the diligent documentation of the manual testing steps, it really helps a lot when doing the review!

2022-11-20 17:04 UTC, merged