fix(general): fixed unused deps and updated them
hyperledger/cactus pull request #581
Opened 2021-02-11 16:56 UTC by kikoncuo

Only updated package.jsons dependencies, ran depcheck to delete unused packages and tests

Signed-off-by: Enrique Alcázar <e.alcazar.garzas@accenture.com>

2021-02-16 15:02 UTC, kikoncuo commented
Latest version of  fabric  SDK (1.4.17) breaks compatibility for fabric 1.4.x and 2.x due to a hubs timeout error.

```
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts 1> 2021-02-15T22:41:35.825Z - warn: [TransactionEventHandler]: _strategyFail: strategy fail for transaction "3fcba282f505c36728e693b36940c2d7397fcddb598cf0fa130f12647d5ed849": TimeoutError: Event strategy not satisfied within the timeout period. No response received from event hubs: peer0.org1.example.com, peer1.org1.example.com:8051, peer0.org2.example.com:9051, peer1.org2.example.com:10051
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts 1>     at TransactionEventHandler._timeoutFail (/mnt/c/Users/enriq/Accenture/Cactus/packages/cactus-plugin-ledger-connector-fabric/node_modules/fabric-network/lib/impl/event/transactioneventhandler.js:101:17)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts 1>     at Timeout._onTimeout (/mnt/c/Users/enriq/Accenture/Cactus/packages/cactus-plugin-ledger-connector-fabric/node_modules/fabric-network/lib/impl/event/transactioneventhandler.js:78:15)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts 1>     at listOnTimeout (internal/timers.js:554:17)
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts 1>     at processTimers (internal/timers.js:497:7) {
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts 1>   transactionId: '3fcba282f505c36728e693b36940c2d7397fcddb598cf0fa130f12647d5ed849'   
packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts 1> }
 FAIL  packages/cactus-plugin-ledger-connector-fabric/src/test/typescript/integration/fabric-v1-4-x/run-transaction-endpoint-v1.test.ts
 ✖ Error: Request failed with status code 500
```

Moved everything to the latest version we used 1.4.11

2021-02-16 18:29 UTC, petermetz requested changes
@kikoncuo Tried running `npm run build:dev` and got

```sh


lerna ERR! npm run build:dev:frontend stderr:
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @ionic/angular : es2015 as esm2015
- Generating browser application bundles...

Compiling @ionic-native/core : module as esm5
✔ Browser application bundle generation complete.

Error: Cannot read property 'tapAsync' of undefined

Error: ./src/global.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: Cannot read property 'tapAsync' of undefined
    at ExternalModuleFactoryPlugin.apply (/cactus-origin/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:59:39)
    at /cactus-origin/node_modules/webpack/lib/ExternalsPlugin.js:30:63
    at SyncHook.eval [as call] (eval at create (/cactus-origin/packages/cactus-cockpit/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:1)
    at SyncHook.lazyCompileHook (/cactus-origin/packages/cactus-cockpit/node_modules/tapable/lib/Hook.js:154:20)
    at /cactus-origin/packages/cactus-cockpit/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:665:23
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/cactus-origin/packages/cactus-cockpit/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/cactus-origin/packages/cactus-cockpit/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/cactus-origin/packages/cactus-cockpit/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:662:28)
    at Compiler.runAsChild (/cactus-origin/packages/cactus-cockpit/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:328:8)
    at Object.pitch (/cactus-origin/packages/cactus-cockpit/node_modules/mini-css-extract-plugin/dist/loader.js:121:17)
 @ multi ./src/theme/variables.scss ./src/global.scss styles[1]

Error: ./src/theme/variables.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: Cannot read property 'tapAsync' of undefined
    at ExternalModuleFactoryPlugin.apply (/cactus-origin/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:59:39)
    at /cactus-origin/node_modules/webpack/lib/ExternalsPlugin.js:30:63
    at SyncHook.eval [as call] (eval at create (/cactus-origin/packages/cactus-cockpit/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:1)
    at SyncHook.lazyCompileHook (/cactus-origin/packages/cactus-cockpit/node_modules/tapable/lib/Hook.js:154:20)
    at /cactus-origin/packages/cactus-cockpit/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:665:23
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/cactus-origin/packages/cactus-cockpit/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at AsyncSeriesHook.lazyCompileHook (/cactus-origin/packages/cactus-cockpit/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.compile (/cactus-origin/packages/cactus-cockpit/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:662:28)
    at Compiler.runAsChild (/cactus-origin/packages/cactus-cockpit/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:328:8)
    at Object.pitch (/cactus-origin/packages/cactus-cockpit/node_modules/mini-css-extract-plugin/dist/loader.js:121:17)
 @ multi ./src/theme/variables.scss ./src/global.scss styles[0]


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @hyperledger/cactus-cockpit@0.3.0 build:dev:frontend: `ng build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @hyperledger/cactus-cockpit@0.3.0 build:dev:frontend script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2021-02-16T18_25_40_022Z-debug.log

lerna ERR! npm run build:dev:frontend exited 1 in '@hyperledger/cactus-cockpit'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @hyperledger/cactus@ build:dev:frontend: `lerna run build:dev:frontend`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @hyperledger/cactus@ build:dev:frontend script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2021-02-16T18_25_40_040Z-debug.log
ERROR: "build:dev:frontend" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @hyperledger/cactus@ build:dev: `npm-run-all build:dev:backend webpack:dev:web build:dev:frontend`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @hyperledger/cactus@ build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2021-02-16T18_25_40_052Z-debug.log
~/a/blockchain/cactus-origin$ 
```

2021-02-16 18:36 UTC, petermetz commented
Related issue is the one where we'd start executing the full CI script in the GH actions (if that issue was already resolved then the CI would've caught this in the PR automatically as well) 
https://github.com/hyperledger/cactus/issues/497

2021-03-08 15:09 UTC, petermetz requested changes
@kikoncuo 
The cockpit UI doesn't work still unfortunately

```
npm run start:api-server
```

```
$ curl --insecure https://127.0.0.1:3000
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: ENOENT: no such file or directory, stat *REDACTED_PATH*/packages/cactus-cmd-api-server/node_modules/@hyperledger/cactus-cockpit/www/index.html</pre>
</body>
</html>

```

2021-03-25 16:41 UTC, petermetz approved these changes

2021-03-29 11:14 UTC, takeutak approved these changes

2021-03-30 04:45 UTC, merged