feat(quorum): add prometheus exporter
hyperledger/cactus pull request #602
Opened 2021-02-26 07:28 UTC by jagpreetsinghsasan

# Commit to be reviewed
---------------------------------

feat(quorum): prometheus exporter metrics integration
	
	Primary Change
	--------------

	1. The quorum ledger connector plugin now includes the prometheus metrics exporter integration
	2. OpenAPI spec now has api endpoint for the getting the prometheus metrics

	Refactorings that were also necessary to accomodate 1) and 2)
	------------------------------------------------------------

	3. GetPrometheusMetricsV1 class is created to handle the corresponding api endpoint
	4. IPluginLedgerConnectorQuorumOptions interface in PluginLedgerConnectorQuorum class now has a prometheusExporter optional field
	5. The PluginLedgerConnectorQuorum class has relevant functions and codes to incorporate prometheus exporter
	6. deploy-contract-from-json.test.ts is changed to incorporate the prometheus exporter
	7. Added Readme.md on the prometheus exporter usage

	Fixes #534

Signed-off-by: Jagpreet Singh Sasan <jagpreet.singh.sasan@accenture.com>

2021-02-26 23:26 UTC, petermetz submitted a review, later dismissed

2021-03-01 13:12 UTC, takeutak reviewed
I think there is almost no problem. However, could you please reply to or revise your comments on minor points?

2021-03-02 05:25 UTC, jagpreetsinghsasan commented on packages/cactus-plugin-ledger-connector-quorum/README.md
> +# `@hyperledger/cactus-plugin-ledger-quorum`
Fixed.

2021-03-03 05:47 UTC, takeutak submitted a review, later dismissed

2021-03-15 17:35 UTC, takeutak approved these changes

2021-03-17 03:32 UTC, petermetz requested changes

2021-03-19 05:01 UTC, petermetz submitted a review, later dismissed

2021-03-23 05:30 UTC, takeutak submitted a review, later dismissed

2021-03-24 07:13 UTC, takeutak approved these changes

2021-03-25 03:12 UTC, petermetz commented
@jagpreetsinghsasan I recommend rebasing this to the PR that improves the GHA flakiness (and then also making sure to mark this as dependent on that) 
This is the one: #713

2021-03-28 04:58 UTC, petermetz commented
@jagpreetsinghsasan After rebasing to main the CI will hopefully pass and then this is ready to go

2021-03-28 04:58 UTC, petermetz approved these changes

2021-03-30 00:17 UTC, merged