feat(connector-besu): common interface invoke-contract
hyperledger/cactus pull request #677
Opened 2021-03-17 13:42 UTC by AzaharaC

Resolve #609 
Depends on #671 

When the pr that this depends on is merged, it may be necessary to make changes to the invokeContractV2 function. 
(this is just a possibility but not sure)

Signed-off-by: AzaharaC <a.castano.benito@accenture.com>

2021-03-22 08:44 UTC, kikoncuo commented
Timeout in the tests, we need to review the testing pipeline this is happening for most new PRs

@petermetz

2021-03-22 15:44 UTC, petermetz commented
> Timeout in the tests, we need to review the testing pipeline this is happening for most new PRs
> 
> @petermetz

@kikoncuo Please up-vote my PR(s) on the mailing list, hopefully the fix will get fast tracked for approval :-) (sent out the email just a few hours before your comment)

2021-03-24 14:48 UTC, petermetz requested changes

2021-03-24 14:48 UTC, petermetz commented on packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
> +    {
@AzaharaC I think this might've become redundant after a rebase (there's already `InvokeContractEndpointV2` registered in the same function)

2021-03-24 17:12 UTC, petermetz approved these changes

2021-03-24 22:41 UTC, takeutak approved these changes

2021-03-24 23:04 UTC, merged