feat(connector-besu): filesystem replaced by keychain
hyperledger/cactus pull request #702
Opened 2021-03-22 09:19 UTC by jordigiam

Resolve #678

2021-03-24 15:13 UTC, petermetz requested changes
@jordigiam When we generate the changelogs at release time, with the current commit message, this will show up as besu getting the keychain support, but there will be nothing there about quorum. Is there any chance that you could either break it up into two commits (it's OK to keep the PR as is, with 2 commits because they are doing the same change anyway) like
Commit 1 `feat(connector-besu): filesystem replaced by keychain`
Commit 2 `feat(connector-quorum): filesystem replaced by keychain`

Or you could also leave it in one commit and just edit the scope to include both besu and quorum like
`feat(connector-besu,connector-quorum): filesystem replaced by keychain`
Assuming it's not over the character limit this would work as well. Also any other solution that makes sure that the generated changelogs will mention both quorum and besu would work for me, but I only know of the two options above to make it so.

2021-04-07 09:07 UTC, jordigiam commented on packages/cactus-plugin-ledger-connector-besu/src/main/typescript/plugin-ledger-connector-besu.ts
>              `${fnTag} Cannot create an instance of the contract because the contractName and the contractName of the JSON doesn't match`,
Done!

2021-04-07 16:18 UTC, petermetz requested changes
@jordigiam Just tracking/noting down for the record here what we discussed on the pair programming session today => please make sure that the request can always override whatever is in `this.contracts` by using the keychain instead.

2021-04-09 17:40 UTC, petermetz approved these changes
LGTM

Note to self: We need to put in some time to design something that's stateless so that the contracts map can be eliminated entirely (somehow, but I don't know any better right now either except for the consortium database, but that's also not a mature design for contract storage so back to my initial point about putting time into some design...)

One thing I noticed is that we could expose a get network ID endpoint on the web3 flavored connectors (besu, quorum) so that we can build on that in the future by requiring the caller to fill the network ID themselves and freeing the connector from having to do that altogether.

2021-04-12 08:38 UTC, takeutak approved these changes

2021-04-12 09:34 UTC, merged