fix(connector-corda): container image kotlin compilation fails in model
hyperledger/cactus pull request #879
Opened 2021-04-28 09:49 UTC by travis-payne

This change fixes the compilation error kotlin was throwing when building the docker image.

BREAKING CHANGE: 🧨 We're now using the latest OpenAPI Generator CLI version of 2.2.6, so quite a few autogenerated files have been changed.

- Enums generated by OpenAPI are now lowercase.
- API Clients now need to instantiate a Configuration object and use that as a constructor param.
- Now using Integer as opposed to Number in the OpenAPI config to prevent an error when mapping to BigDecimal

✅ Closes: #763 and #584

2021-04-28 15:04 UTC, petermetz requested changes

2021-04-28 18:52 UTC, petermetz commented
@travis-payne FYI these errors are caused by the imports with relative paths that I commented on maybe once, but there could've been a few more that I missed, I'm not sure:
https://github.com/hyperledger/cactus/pull/879/checks?check_run_id=2458629533#step:5:17198

2021-04-28 19:23 UTC, petermetz approved these changes

2021-05-10 06:23 UTC, takeutak approved these changes

2021-05-19 23:02 UTC, petermetz commented
@travis-payne 0.5.0 is out now, freeze is over, please rebase + squash this branch and then we can finally merge it in.

2021-05-29 20:15 UTC, merged