Cleanup electricity-trade example docker containers and fix readme.
hyperledger/cactus pull request #989
Opened 2021-05-26 18:01 UTC by rybalko

2021-05-27 23:20 UTC, petermetz commented
@rybalko Thank you very much for the contribution! Please do the following:
1. squash to a single commit
2. write the commit message according to the conventional commits guide lines (see CONTRIBUTING.md)
3. rebase onto the latest main
4. fix the DCO (see CONTRIBUTING.md)

2021-05-28 08:09 UTC, takeutak commented on examples/electricity-trade/cleanup.sh
> +docker stop gethtestnet_init-chain-geth1_run_1
Would you remove "docker stop gethtestnet_init-chain-geth1_run_1"? This container will be stopped when geth1 container is launched.

2021-05-28 08:10 UTC, takeutak commented on examples/electricity-trade/cleanup.sh
> +docker stop gethtestnet_init-chain-geth1_run_2
Would you remove "docker stop gethtestnet_init-chain-geth1_run_2"? The reason is like the above.

2021-05-28 08:10 UTC, takeutak commented on examples/electricity-trade/cleanup.sh
> +docker rm gethtestnet_init-chain-geth1_run_1
Would you remove "docker rm gethtestnet_init-chain-geth1_run_1"? The reason is like the above.

2021-05-28 08:13 UTC, takeutak commented on examples/electricity-trade/cleanup.sh
> +sudo rm ../../tools/docker/geth-testnet/data-geth1/geth.ipc*
This is only a comment (not a change request) that I'm wondering that the error message "rm: cannot remove '../../tools/docker/geth-testnet/data-geth1/geth.ipc*': No such file or directory" happens (but the file ../../tools/docker/geth-testnet/data-geth1/geth.ipc is removed by this script)
I will accept this change once it is harmless.  If an improvement is found, this part may be fixed on later pull-requests.

2021-05-28 08:20 UTC, takeutak commented
@rybalko Thank you for your intelligent commit to our code! I think your PR is helpful for us.
For the code itself, I appreciate if you could consider about my above points.
Also, as @petermetz said, there are some manner of pull-request in Cactus. So could you reflect the @petermetz 's points?
It may be difficult, but if you are in trouble, please leave a comment. I will help you then. Good luck!

2021-05-31 14:04 UTC, rybalko commented
Hello @takeutak 
perhaps it is better to cancel this pull request then and I'll revert my commits to our opentaps/cactus repo
and made new one with readme changes and cleanup.sh and correct description

about
sudo rm -R ../../tools/docker/geth-testnet/data-geth1/geth
sudo rm ../../tools/docker/geth-testnet/data-geth1/geth.ipc*
I just noticed during start/stop electricity-trade example several times 
that it could keeps those directory and file, and they are with 'root' access
what is cause error in next run
so I decided clean up them

2021-05-31 16:09 UTC, takeutak commented
@rybalko Thanks! 

> perhaps it is better to cancel this pull request then and I'll revert my commits to our opentaps/cactus repo
and made new one with readme changes and cleanup.sh and correct description

That's sounds great! I'm looking forward to your new pull-request.

> about
> sudo rm -R ../../tools/docker/geth-testnet/data-geth1/geth
> sudo rm ../../tools/docker/geth-testnet/data-geth1/geth.ipc*
> I just noticed during start/stop electricity-trade example several times
> that it could keeps those directory and file, and they are with 'root' access
> what is cause error in next run
> so I decided clean up them

Great! As you said, I agree with your idea that cleanup.sh includes the above commands.

I think it is a good Pull-request, so I would like to ask you to post it. If you have any trouble, please post a comment. Good luck!

2021-06-01 22:36 UTC, petermetz requested changes
@rybalko See my comment above for the changes requested from my side.

2021-06-03 08:55 UTC, closed without merging

2021-06-03 21:44 UTC, petermetz commented
@rybalko For future reference: You don't need to close/recreate PRs from scratch, you can also just force push to your branch instead when history needs to be altered.